//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionsAssignedToEachPerson
    {
        public int FK_quesstionId { get; set; }
        public int FK_userId { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<bool> isAnswered { get; set; }
    
        public virtual questions questions { get; set; }
        public virtual users users { get; set; }
    }
}
